sources:
    - ../../..
templates:
    - Templates/Mockable.swifttemplate
output:
    path: ../../../AutoMockableTests/Codegen/Generated
    link:
        project: AutoMockable
        target: AutoMoackableTests
        group: AutoMockableTests/Codegen/Generated
